export const PDD_SELECTORS = Object.freeze({
  conversationItems: [
    '.chat-item',
    '[data-conversation-id]',
    '[data-session-id]',
    '[data-chat-id]',
    '[class*="conversation-item"]',
    '[class*="session-item"]',
    '[class*="chat-list-item"]',
  ],
  conversationName: [
    '.chat-nickname',
    '[data-role="customer-name"]',
    '[class*="nickname"]',
    '[class*="user-name"]',
    '[class*="customer-name"]',
    '[class*="title"]',
  ],
  conversationPreview: [
    '.bottom-message',
    '[data-role="message-preview"]',
    '[class*="last-message"]',
    '[class*="message-preview"]',
    '[class*="summary"]',
  ],
  unreadBadge: [
    '.SessionBaseCard-unread-rot',
    '[data-role="unread-count"]',
    '.ant-badge-count',
    '.ant-badge-dot',
    '.semi-badge',
    '.semi-badge-dot',
    '[class*="unread"]',
    '[class*="badge"]',
  ],
  messageItems: [
    'li[id^="middlePanel_List_"]',
    '.msg-list li.onemsg',
    '.onemsg',
    '[data-message-id]',
    '[data-msg-id]',
    '[class*="message-item"]',
    '[class*="msg-item"]',
    '[class*="chat-message"]',
  ],
  messageContainers: [
    '#message-panel',
    '.msg-list',
    '[data-role="message-list"]',
    '[class*="MessageList"]',
    '[class*="message-list"]',
    '[class*="messageList"]',
    '[class*="msg-list"]',
  ],
  messageContent: [
    '.kwaishop-cs-BizTextCard',
    '[class*="BizTextCard"]',
    '.msg-content',
    '[data-role="message-content"]',
    '[class*="message-content"]',
    '[class*="msg-content"]',
    '[class*="text-content"]',
    '[class*="bubble"]',
  ],
  messageTime: [
    '.message-time',
    'time',
    '[data-role="message-time"]',
    '[class*="message-time"]',
    '[class*="msg-time"]',
    '[class*="timestamp"]',
  ],
  shopName: [
    '.LoginUserInfo-mainTitle-text',
    '[class*="LoginUserInfo-mainTitle-text"]',
    '[class*="LoginUserInfo"] [class*="mainTitle"]',
    '[data-role="shop-name"]',
    '.shop-name',
    '[class*="shopName"]',
    '[class*="ShopName"]',
    '[class*="mall-name"]',
    '[class*="shop-name"]',
    '[class*="store-name"]',
  ],
  latestOrdersTab: [
    '[data-role="latest-orders"]',
    '[class*="LatestOrder"]',
    '[class*="latest-order"]',
  ],
  personalOrdersTab: [
    '[data-role="personal-orders"]',
    '[class*="PersonalOrder"]',
    '[class*="personal-order"]',
  ],
  orderCards: [
    '[data-order-id]',
    '[class*="OrderCard"]',
    '[class*="order-card"]',
    '[class*="OrderItem"]',
  ],
});

export function serializedSelectorArgument(rules = null) {
  return `--pdd-adapter-config=${encodeURIComponent(JSON.stringify({ selectors: PDD_SELECTORS, rules }))}`;
}
