'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{randomBytes}=require('node:crypto');
const {TARGET,buildAbilityInvocation,validateSource,summarizeCallback}=require('./protocol.cjs'); const {installTransferProbe}=require('./page.cjs');
const DIR=path.resolve(__dirname,'../../.tmp/qn-transfer-probe'),PORT=18092;
const request=(kind,page)=>kind==='list'?{method:'mtop.taobao.mmp.subuser.page.get',version:'1.0',httpMethod:'get',param:JSON.stringify({nick:TARGET.sourceNick,page_no:String(page),page_size:'5'})}:{method:'mtop.taobao.qianniu.cloudkefu.accountstatus.getbyid',version:'1.0',httpMethod:'get',param:JSON.stringify({main_account_id:TARGET.mainUid})};
function prepare(){fs.mkdirSync(DIR,{recursive:true});const attempt=path.join(DIR,'attempt.json');if(fs.existsSync(attempt)){const stamp=Date.now();fs.renameSync(attempt,path.join(DIR,'attempt-finished-'+stamp+'.json'));if(fs.existsSync(path.join(DIR,'result.json')))fs.renameSync(path.join(DIR,'result.json'),path.join(DIR,'result-finished-'+stamp+'.json'));}const f=path.join(DIR,'config.json');const c={...TARGET,base:'http://127.0.0.1:'+PORT,token:randomBytes(32).toString('hex'),param:buildAbilityInvocation(TARGET).param};fs.writeFileSync(f,JSON.stringify(c));fs.writeFileSync(path.join(DIR,'page.js'),'('+installTransferProbe.toString()+')(window,'+JSON.stringify(c)+');');console.log('prepared');}
function unwrap(raw){let v=JSON.parse(raw),i=0;while(v&&!v.api&&i++<4)v=typeof(v.result??v.data)==='string'?JSON.parse(v.result??v.data):(v.result??v.data);return v;}
function main(){const cmd=process.argv[2];if(cmd==='prepare')return prepare();const c=JSON.parse(fs.readFileSync(path.join(DIR,'config.json')));let phase='idle',page=null,queue=[],active=null,records=[];const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;if(origin==='https://alires-webui')res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'POST, GET','Access-Control-Allow-Headers':'Content-Type'});return res.end();}let b='';for await(const x of req)b+=x;let j={};try{j=JSON.parse(b)}catch{};const out=x=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(x));};if(j.token!==c.token)return out({error:'auth'});if(req.url==='/poll'){page={pageId:j.pageId,state:j.state};if(!j.state?.shopUid||!j.state?.mainUid||!j.state?.nick)return out({job:null});try{validateSource(j.state)}catch{return out({stop:true})}const job=phase==='running'&&!active? (active=queue.shift()):null;out({job:job||null,stop:phase==='finished'});return}if(req.url==='/run'){if(phase!=='idle'||!page)return out({error:'need fresh page'});fs.writeFileSync(path.join(DIR,'attempt.json'),JSON.stringify({startedAt:new Date().toISOString(),target:TARGET}));phase='running';queue=[{kind:'read',request:request('status')}];out({queued:true,plan:'fresh-status-then-transfer'});return}if(req.url==='/result'){records.push({at:new Date().toISOString(),kind:j.kind,result:j.result});active=null;if(j.kind==='read'){let raw=j.result?.raw||'',online=false;try{const x=unwrap(raw);online=Array.isArray(x?.data?.module)&&x.data.module.some(a=>String(a.accountId)===TARGET.targetUid&&(a.pcOnline===true||a.mobileOnline===true)&&a.suspend===false)}catch{}if(!j.result?.ok||!online){phase='finished';return out({ok:false,error:'target not confirmed online; transfer not invoked'})}queue.push({kind:'transfer'});}if(j.kind==='transfer'){const summary=summarizeCallback(j.result);fs.writeFileSync(path.join(DIR,'result.json'),JSON.stringify({target:TARGET,receivedAt:new Date().toISOString(),...summary},null,2));phase='finished'}out({ok:true});return}if(req.url==='/status')return out({phase,page,records});out({});});server.listen(PORT,'127.0.0.1',()=>console.log('listening '+PORT));}
main();
