param([switch]$Remove)
$ErrorActionPreference='Stop'
$versions=@(Get-Process AliWorkbench -ErrorAction SilentlyContinue|ForEach-Object{try{$_.Modules|Where-Object ModuleName -eq 'AppFramework.dll'|ForEach-Object{[IO.Path]::GetDirectoryName($_.FileName)}}catch{}}|Sort-Object -Unique)
if($versions.Count -ne 1){throw 'Cannot identify exactly one running Qianniu version'}
$data=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../.tmp/qn-transfer-probe'));$zipPath=Join-Path $versions[0] 'Resources/newWebui/webui.zip';Add-Type -AssemblyName System.IO.Compression.FileSystem
function Hashes($f){$z=[IO.Compression.ZipFile]::OpenRead($f);$h=@{};try{foreach($e in $z.Entries){$s=$e.Open();try{$h[$e.FullName]=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($s))}finally{$s.Dispose()}}}finally{$z.Dispose()};$h}
$beforeHash=(Get-FileHash $zipPath -Algorithm SHA256).Hash;$z=[IO.Compression.ZipFile]::OpenRead($zipPath);try{$e=$z.GetEntry('web_chat-packer/recent.html');$r=[IO.StreamReader]::new($e.Open());try{$old=$r.ReadToEnd()}finally{$r.Dispose()}}finally{$z.Dispose()}
$html=[regex]::Replace($old,'(?s)\s*<!-- qn-transfer-probe-start -->.*?<!-- qn-transfer-probe-end -->','');if(!$Remove){$script=Get-Content (Join-Path $data 'page.js') -Raw -Encoding UTF8;if($script-match'</script'){throw 'Invalid inline script'};$anchor='<script src="./recent/vendor.js"></script>';if(([regex]::Matches($html,[regex]::Escape($anchor))).Count-ne 1){throw 'Ambiguous insertion point'};$add="<!-- qn-transfer-probe-start --><script>`n$script`n</script><!-- qn-transfer-probe-end -->";$html=$html.Replace($anchor,$add+"`n"+$anchor)}
$stamp=Get-Date -Format yyyyMMdd-HHmmssfff;$backup=Join-Path $data "webui-before-$stamp.zip";Copy-Item $zipPath $backup;$staged=Join-Path ([IO.Path]::GetDirectoryName($zipPath)) ('transfer-staged-'+[guid]::NewGuid().ToString('N')+'.zip');Copy-Item $backup $staged;$z=[IO.Compression.ZipFile]::Open($staged,[IO.Compression.ZipArchiveMode]::Update);try{$z.GetEntry('web_chat-packer/recent.html').Delete();$e=$z.CreateEntry('web_chat-packer/recent.html');$w=[IO.StreamWriter]::new($e.Open(),[Text.UTF8Encoding]::new($false));try{$w.Write($html)}finally{$w.Dispose()}}finally{$z.Dispose()}
$b=Hashes $backup;$a=Hashes $staged;if($b.Count-ne $a.Count){throw 'ZIP entry count changed'};$changed=@($b.Keys|Where-Object{$b[$_]-ne $a[$_]});if($changed.Count-ne 1-or$changed[0]-ne 'web_chat-packer/recent.html'){throw 'Unexpected resource change'};if((Get-FileHash $zipPath -Algorithm SHA256).Hash-ne $beforeHash){throw 'Qianniu resources changed while staging'};[IO.File]::Replace($staged,$zipPath,($staged+'.bak'));Write-Output "Installed transfer probe; backup: $backup; reboot required"
